# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run_server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('validator/templates', 'validator/templates'),
        ('yml_validator/settings.py', 'yml_validator'),
        ('yml_validator/urls.py', 'yml_validator'),
        ('yml_validator/wsgi.py', 'yml_validator'),
        ('yml_validator/__init__.py', 'yml_validator'),
        ('validator/__init__.py', 'validator'),
        ('validator/admin.py', 'validator'),
        ('validator/apps.py', 'validator'),
        ('validator/models.py', 'validator'),
        ('validator/urls.py', 'validator'),
        ('validator/views.py', 'validator'),
        ('manage.py', '.'),
        ('db.sqlite3', '.'),
    ],
    hiddenimports=[
        'django',
        'django.core.management',
        'django.core.management.commands',
        'django.core.management.commands.runserver',
        'django.contrib.staticfiles',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'validator',
        'validator.views',
        'validator.urls',
        'yml_validator.settings',
        'yml_validator.urls',
        'yaml',
        'json',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='yml-validator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
